In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [52]:
df = pd.read_csv("C://Users//REGEN//Documents//python libraries//machine learning//save_model_with_pickle_joblib//homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
# Create linear regression object
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [12]:
# value of coffecient (means slope) from y = mx + b
reg.coef_

array([135.78767123])

In [14]:
# value of intercept

reg.intercept_

180616.43835616432

In [16]:
# predict the price of area 5000 sqft

reg.predict([[5000]])

C:\Users\REGEN\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [34]:
# Save Model To a File Using Python Pickle

import pickle

In [36]:
# Load Saved Model
# wb for writing also binary mode is important
with open('model_pickle', 'wb') as f:
    pickle.dump(reg,f)

In [28]:
 # rb for reading also binary mode is important
with open('model_pickle', 'rb') as f:
     model = pickle.load(f)

In [32]:
model.predict([[5000]])

C:\Users\REGEN\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [48]:
#Save Trained Model Using joblib
# if your model consist of large numpy array then using joblib might be more efficient

import joblib

In [54]:
# save the model
joblib.dump(reg, 'C://Users//REGEN//Documents//python libraries//machine learning//save_model_with_pickle_joblib//model_joblib')

['C://Users//REGEN//Documents//python libraries//machine learning//save_model_with_pickle_joblib//model_joblib']

In [56]:
# load the model

mj = joblib.load("C://Users//REGEN//Documents//python libraries//machine learning//save_model_with_pickle_joblib//model_joblib")

In [58]:
mj.predict([[5000]])

C:\Users\REGEN\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])