In [1]:
import numpy as np
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
for row in a:
    for cell in row:
        print(cell)
    print(row)

0
1
2
3
[0 1 2 3]
4
5
6
7
[4 5 6 7]
8
9
10
11
[ 8  9 10 11]


In [9]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
#printing row by row is c-order
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [15]:
#printing column by column is fortran-order
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [17]:
# flags to print entire column in one iteration
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [21]:
# optional flags to iterate in array you can modify the element
for x in np.nditer(a, order='F', op_flags=['readwrite']):
    x[...] = x*x
a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

In [23]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [25]:
# iterate through both array simultaniously, shape and dimension is same
#broadcasting rule:  
# they are equal, or
#one of them is 1
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
16 3
81 3
256 7
625 7
1296 7
2401 7
4096 11
6561 11
10000 11
14641 11
